### ISSUE TITLE
Not Working on Chrome Version 94.0.4606.71 (Official Build) (arm64)

### ISSUE THREAD

**Issue by dooleyb1** [macleanjr/gh-labels-in-jira#29]
Hey there, first of all thanks for this plugin, myself & my entire team have been using it for over a year now and it has been a fantastic help to moving our sprints along and upping our productive capacity.

However, just in the last few days the labels have stopped appearing in Jira. I've tried creating a new access token with the `repo` scope which has not helped either.

Any idea what may be causing this? 

Thanks!

**Comment by macleanjr** [comment]
Hi @dooleyb1 ! Sorry for the late reply — Atlassian changed the URL structure and caused the extension to not fire properly.  I pushed out an update a few days after you opened the issue — can you let me know if you're still having the issue?

**Comment by dooleyb1** [comment]
Hey @macleanjr , no worries. No the plugin is back up online and working seamlessly now. Thanks again!
